name: Run unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read
  issues: write
  checks: write

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true
      - name: Use Node JS LTS 20.x & using pnpm for caching
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - name: Run unit tests
        run: pnpm run test:prod
      - name: Report test results (LRU)
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/test-results-lru.xml'
          check_name: 'LRU Cache Test Report'
      - name: Report test results (SSML)
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/test-results-ssml.xml'
          check_name: 'SSML Test Report'
